//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerrysJunkTrunk.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GerrysJunkTrunk.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye..
        /// </summary>
        public static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerry&apos;s price:.
        /// </summary>
        public static string GerrysPrice {
            get {
                return ResourceManager.GetString("GerrysPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerry&apos;s Junk Trunk.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerry&apos;s Junk Trunk Sales.
        /// </summary>
        public static string HeaderSales {
            get {
                return ResourceManager.GetString("HeaderSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for installing Gerry&apos;s Junk Trunk!.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Gerry&apos;s trunk is initially limited to ten spaces..
        /// </summary>
        public static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - You can only build one..
        /// </summary>
        public static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Once items go in, they don&apos;t come out..
        /// </summary>
        public static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Items in the trunk are sold when the day ends (moon a little past the church)..
        /// </summary>
        public static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - You get more at the vendor. Gerry takes a cut of the profits..
        /// </summary>
        public static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The trunk has three levels of progress, initial unlock and then two enhancements, linked to certain tech/perks..
        /// </summary>
        public static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy! - p1xel8ted.
        /// </summary>
        public static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?! Nothing!.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted at: Yard build desk. Has 10 slots with a max stack size of 50..
        /// </summary>
        public static string Stage1Des {
            get {
                return ResourceManager.GetString("Stage1Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create: Gerry&apos;s Junk Trunk..
        /// </summary>
        public static string Stage1Header {
            get {
                return ResourceManager.GetString("Stage1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerry&apos;s junk trunk is expanded! Now has 20 slots with a max stack size of 50..
        /// </summary>
        public static string Stage2Des {
            get {
                return ResourceManager.GetString("Stage2Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance: Gerry&apos;s Junk Trunk.
        /// </summary>
        public static string Stage2Header {
            get {
                return ResourceManager.GetString("Stage2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerry takes a smaller cut of the profits and max stack size increased to 100..
        /// </summary>
        public static string Stage3Des {
            get {
                return ResourceManager.GetString("Stage3Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance: Gerry&apos;s Junk Trunk.
        /// </summary>
        public static string Stage3Header {
            get {
                return ResourceManager.GetString("Stage3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work. Work..
        /// </summary>
        public static string WorkWork {
            get {
                return ResourceManager.GetString("WorkWork", resourceCulture);
            }
        }
    }
}
