namespace BeamMeUpGerry;

internal static class Language
{
    internal enum Terms
    {
        ZoneLClay,
        ZoneLCoal,
        ZoneLFellingSite,
        ZoneLLighthouse,
        ZoneLQuarry,
        ZoneLSand,
        ZoneLFarmer,
        ZoneLMill,
        Page1,
        Page2,
        Page3,
        Page4,
        Page5,
        Page6,
        Page7,
        Page8,
        Page9,
        Page10,
        CantUseHere,
        CustomLocations,
        DontKnow,
        InTutorial,
        InTutorialNoStone,
        M1,
        M10,
        M2,
        M3,
        M4,
        M5,
        M6,
        M7,
        M8,
        M9,
        MoreCoin,
        WhereIsIt,
        None
    }

    private static readonly Dictionary<Terms, string> TermMap = new()
    {
        {Terms.ZoneLClay, Constants.ZoneLClay},
        {Terms.ZoneLCoal, Constants.ZoneLCoal},
        {Terms.ZoneLFellingSite, Constants.ZoneLFellingsite},
        {Terms.ZoneLLighthouse, Constants.ZoneLLighthouse},
        {Terms.ZoneLQuarry, Constants.ZoneLQuarry},
        {Terms.ZoneLSand, Constants.ZoneLSand},
        {Terms.ZoneLFarmer, Constants.ZoneLFarmer},
        {Terms.ZoneLMill, Constants.ZoneLMill},
        {Terms.Page1, Constants.Page1},
        {Terms.Page2, Constants.Page2},
        {Terms.Page3, Constants.Page3},
        {Terms.Page4, Constants.Page4},
        {Terms.Page5, Constants.Page5},
        {Terms.Page6, Constants.Page6},
        {Terms.Page7, Constants.Page7},
        {Terms.Page8, Constants.Page8},
        {Terms.Page9, Constants.Page9},
        {Terms.Page10, Constants.Page10},
        {Terms.CantUseHere, Constants.CantUseHere},
        {Terms.CustomLocations, Constants.CustomLocations},
        {Terms.DontKnow, Constants.DontKnow},
        {Terms.InTutorial, Constants.InTutorial},
        {Terms.InTutorialNoStone, Constants.InTutorialNoStone},
        {Terms.M1, Constants.M1},
        {Terms.M10, Constants.M10},
        {Terms.M2, Constants.M2},
        {Terms.M3, Constants.M3},
        {Terms.M4, Constants.M4},
        {Terms.M5, Constants.M5},
        {Terms.M6, Constants.M6},
        {Terms.M7, Constants.M7},
        {Terms.M8, Constants.M8},
        {Terms.M9, Constants.M9},
        {Terms.MoreCoin, Constants.MoreCoin},
        {Terms.WhereIsIt, Constants.WhereIsIt}
    };

    private static readonly Dictionary<string, Dictionary<string, string>> LanguageDictionaries = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Clay pit"},
            {Constants.ZoneLCoal, "Coal vein"},
            {Constants.ZoneLFellingsite, "Felling site"},
            {Constants.ZoneLLighthouse, "Lighthouse"},
            {Constants.ZoneLQuarry, "Quarry"},
            {Constants.ZoneLSand, "Sand mound"},
            {Constants.ZoneLFarmer, "Farmer"},
            {Constants.ZoneLMill, "Mill"},
            {Constants.Page1, "Page 1"},
            {Constants.Page2, "Page 2"},
            {Constants.Page3, "Page 3"},
            {Constants.Page4, "Page 4"},
            {Constants.Page5, "Page 5"},
            {Constants.Page6, "Page 6"},
            {Constants.Page7, "Page 7"},
            {Constants.Page8, "Page 8"},
            {Constants.Page9, "Page 9"},
            {Constants.Page10, "Page 10"},
            {Constants.CantUseHere, "I can’t use that here, boss!"},
            {Constants.CustomLocations, "Custom Locations"},
            {Constants.DontKnow, "I don't know where that is!"},
            {Constants.InTutorial, "I can’t do that just yet! Something about a tutorial…."},
            {Constants.InTutorialNoStone, "I can’t do that just yet! Something about a tutorial - and you don’t have a teleport stone."},
            {Constants.M1, "Where's my coin?"},
            {Constants.M10, "Money buddy."},
            {Constants.M2, "Hand it over."},
            {Constants.M3, "Coin. Now."},
            {Constants.M4, "You'll make it back in no time."},
            {Constants.M5, "This isn't a charity..."},
            {Constants.M6, "Cough it up buddy."},
            {Constants.M7, "Pleasant trip?"},
            {Constants.M8, "Here again?!"},
            {Constants.M9, "Are we there yet?"},
            {Constants.MoreCoin, "You need more coin!"},
            {Constants.WhereIsIt, "Where did I leave that stone..."}
        },
        ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Fosse d'argile"},
            {Constants.ZoneLCoal, "Veine de charbon"},
            {Constants.ZoneLFellingsite, "Site d'abattage"},
            {Constants.ZoneLLighthouse, "Phare"},
            {Constants.ZoneLQuarry, "Carrière"},
            {Constants.ZoneLSand, "Monticule de sable"},
            {Constants.ZoneLFarmer, "Agriculteur"},
            {Constants.ZoneLMill, "Moulin"},
            {Constants.Page1, "Page 1"},
            {Constants.Page2, "Page 2"},
            {Constants.Page3, "Page 3"},
            {Constants.Page4, "Page 4"},
            {Constants.Page5, "Page 5"},
            {Constants.Page6, "Page 6"},
            {Constants.Page7, "Page 7"},
            {Constants.Page8, "Page 8"},
            {Constants.Page9, "Page 9"},
            {Constants.Page10, "Page 10"},
            {Constants.CantUseHere, "Je ne peux pas utiliser ça ici, chef !"},
            {Constants.CustomLocations, "Lieux personnalisés"},
            {Constants.DontKnow, "Je ne sais pas où c'est !"},
            {Constants.InTutorial, "Je ne peux pas encore faire ça ! Quelque chose à propos d'un tutoriel..."},
            {Constants.InTutorialNoStone, "Je ne peux pas encore faire ça ! Quelque chose à propos d'un tutoriel - et tu n'as pas de pierre de téléportation."},
            {Constants.M1, "Où est ma pièce ?"},
            {Constants.M10, "Monnaie, mon pote."},
            {Constants.M2, "Donne-la moi."},
            {Constants.M3, "Pièce. Maintenant."},
            {Constants.M4, "Tu vas le récupérer en un rien de temps."},
            {Constants.M5, "Ce n'est pas une charité..."},
            {Constants.M6, "Crache-la, mon pote."},
            {Constants.M7, "Bon voyage?"},
            {Constants.M8, "Encore ici?!"},
            {Constants.M9, "On est arrivés ?"},
            {Constants.MoreCoin, "Vous avez besoin de plus de pièces !"},
            {Constants.WhereIsIt, "Où ai-je laissé cette pierre..."}
        },
        ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Tongrube"},
            {Constants.ZoneLCoal, "Kohleflöz"},
            {Constants.ZoneLFellingsite, "Fällplatz"},
            {Constants.ZoneLLighthouse, "Leuchtturm"},
            {Constants.ZoneLQuarry, "Steinbruch"},
            {Constants.ZoneLSand, "Sandhaufen"},
            {Constants.ZoneLFarmer, "Bauer"},
            {Constants.ZoneLMill, "Mühle"},
            {Constants.Page1, "Seite 1"},
            {Constants.Page2, "Seite 2"},
            {Constants.Page3, "Seite 3"},
            {Constants.Page4, "Seite 4"},
            {Constants.Page5, "Seite 5"},
            {Constants.Page6, "Seite 6"},
            {Constants.Page7, "Seite 7"},
            {Constants.Page8, "Seite 8"},
            {Constants.Page9, "Seite 9"},
            {Constants.Page10, "Seite 10"},
            {Constants.CantUseHere, "Das kann ich hier nicht verwenden, Chef!"},
            {Constants.CustomLocations, "Benutzerdefinierte Standorte"},
            {Constants.DontKnow, "Ich weiß nicht, wo das ist!"},
            {Constants.InTutorial, "Ich kann das noch nicht tun! Irgendetwas mit einem Tutorial..."},
            {Constants.InTutorialNoStone, "Ich kann das noch nicht tun! Irgendetwas mit einem Tutorial - und du hast keinen Teleportstein."},
            {Constants.M1, "Wo ist mein Geld?"},
            {Constants.M10, "Geld, Kumpel."},
            {Constants.M2, "Gib es her."},
            {Constants.M3, "Geld. Jetzt."},
            {Constants.M4, "Du bekommst es im Handumdrehen zurück."},
            {Constants.M5, "Das ist keine Wohltätigkeit..."},
            {Constants.M6, "Rück es raus, Kumpel."},
            {Constants.M7, "Schöne Reise?"},
            {Constants.M8, "Schon wieder hier?!"},
            {Constants.M9, "Sind wir schon da?"},
            {Constants.MoreCoin, "Du brauchst mehr Münzen!"},
            {Constants.WhereIsIt, "Wo habe ich diesen Stein gelassen..."}
        },
        ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Foso de arcilla"},
            {Constants.ZoneLCoal, "Veta de carbón"},
            {Constants.ZoneLFellingsite, "Sitio de tala"},
            {Constants.ZoneLLighthouse, "Faro"},
            {Constants.ZoneLQuarry, "Cantera"},
            {Constants.ZoneLSand, "Montículo de arena"},
            {Constants.ZoneLFarmer, "Granjero"},
            {Constants.ZoneLMill, "Molino"},
            {Constants.Page1, "Página 1"},
            {Constants.Page2, "Página 2"},
            {Constants.Page3, "Página 3"},
            {Constants.Page4, "Página 4"},
            {Constants.Page5, "Página 5"},
            {Constants.Page6, "Página 6"},
            {Constants.Page7, "Página 7"},
            {Constants.Page8, "Página 8"},
            {Constants.Page9, "Página 9"},
            {Constants.Page10, "Página 10"},
            {Constants.CantUseHere, "¡No puedo usar eso aquí, jefe!"},
            {Constants.CustomLocations, "Ubicaciones personalizadas"},
            {Constants.DontKnow, "¡No sé dónde está eso!"},
            {Constants.InTutorial, "¡No puedo hacer eso todavía! Algo sobre un tutorial..."},
            {Constants.InTutorialNoStone, "¡No puedo hacer eso todavía! Algo sobre un tutorial - y no tienes una piedra de teletransporte."},
            {Constants.M1, "¿Dónde está mi moneda?"},
            {Constants.M10, "Dinero, amigo."},
            {Constants.M2, "Entrégalo."},
            {Constants.M3, "Moneda. Ahora."},
            {Constants.M4, "Lo recuperarás en poco tiempo."},
            {Constants.M5, "Esto no es una caridad..."},
            {Constants.M6, "Suelta eso, amigo."},
            {Constants.M7, "¿Viaje agradable?"},
            {Constants.M8, "¿Aquí de nuevo?!"},
            {Constants.M9, "¿Ya llegamos?"},
            {Constants.MoreCoin, "¡Necesitas más monedas!"},
            {Constants.WhereIsIt, "¿Dónde dejé esa piedra...?"}
        },
        ["pt-br"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Fossa de argila"},
            {Constants.ZoneLCoal, "Veio de carvão"},
            {Constants.ZoneLFellingsite, "Local de corte"},
            {Constants.ZoneLLighthouse, "Farol"},
            {Constants.ZoneLQuarry, "Pedreira"},
            {Constants.ZoneLSand, "Montículo de areia"},
            {Constants.ZoneLFarmer, "Fazendeiro"},
            {Constants.ZoneLMill, "Moinho"},
            {Constants.Page1, "Página 1"},
            {Constants.Page2, "Página 2"},
            {Constants.Page3, "Página 3"},
            {Constants.Page4, "Página 4"},
            {Constants.Page5, "Página 5"},
            {Constants.Page6, "Página 6"},
            {Constants.Page7, "Página 7"},
            {Constants.Page8, "Página 8"},
            {Constants.Page9, "Página 9"},
            {Constants.Page10, "Página 10"},
            {Constants.CantUseHere, "Eu não posso usar isso aqui, chefe!"},
            {Constants.CustomLocations, "Locais Personalizados"},
            {Constants.DontKnow, "Eu não sei onde isso está!"},
            {Constants.InTutorial, "Ainda não posso fazer isso! Algo sobre um tutorial..."},
            {Constants.InTutorialNoStone, "Ainda não posso fazer isso! Algo sobre um tutorial - e você não tem uma pedra de teletransporte."},
            {Constants.M1, "Cadê minha moeda?"},
            {Constants.M10, "Dinheiro, amigo."},
            {Constants.M2, "Entregue."},
            {Constants.M3, "Moeda. Agora."},
            {Constants.M4, "Você vai recuperar em pouco tempo."},
            {Constants.M5, "Isto não é uma caridade..."},
            {Constants.M6, "Desembucha, amigo."},
            {Constants.M7, "Viagem agradável?"},
            {Constants.M8, "Aqui de novo?!"},
            {Constants.M9, "Já chegamos?"},
            {Constants.MoreCoin, "Você precisa de mais moedas!"},
            {Constants.WhereIsIt, "Onde eu deixei aquela pedra..."}
        },
        ["zh-cn"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "黏土坑"},
            {Constants.ZoneLCoal, "煤矿脉"},
            {Constants.ZoneLFellingsite, "伐木场"},
            {Constants.ZoneLLighthouse, "灯塔"},
            {Constants.ZoneLQuarry, "采石场"},
            {Constants.ZoneLSand, "沙堆"},
            {Constants.ZoneLFarmer, "农夫"},
            {Constants.ZoneLMill, "磨坊"},
            {Constants.Page1, "第1页"},
            {Constants.Page2, "第2页"},
            {Constants.Page3, "第3页"},
            {Constants.Page4, "第4页"},
            {Constants.Page5, "第5页"},
            {Constants.Page6, "第6页"},
            {Constants.Page7, "第7页"},
            {Constants.Page8, "第8页"},
            {Constants.Page9, "第9页"},
            {Constants.Page10, "第10页"},
            {Constants.CantUseHere, "我不能在这里使用那个，老板！"},
            {Constants.CustomLocations, "自定义地点"},
            {Constants.DontKnow, "我不知道那在哪里！"},
            {Constants.InTutorial, "我现在还不能做这个！关于教程的事..."},
            {Constants.InTutorialNoStone, "我现在还不能做这个！关于教程的事 - 而且你没有传送石。"},
            {Constants.M1, "我的钱币在哪儿？"},
            {Constants.M10, "钱，兄弟。"},
            {Constants.M2, "交出来。"},
            {Constants.M3, "钱币。现在。"},
            {Constants.M4, "你会很快拿回来的。"},
            {Constants.M5, "这不是慈善..."},
            {Constants.M6, "快点交出来，兄弟。"},
            {Constants.M7, "旅途愉快？"},
            {Constants.M8, "又来了？！"},
            {Constants.M9, "我们到了吗？"},
            {Constants.MoreCoin, "你需要更多的钱币！"},
            {Constants.WhereIsIt, "我把那块石头放在哪了..."}
        },
        ["ko"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "점토 채굴장"},
            {Constants.ZoneLCoal, "석탄 광맥"},
            {Constants.ZoneLFellingsite, "벌채 현장"},
            {Constants.ZoneLLighthouse, "등대"},
            {Constants.ZoneLQuarry, "채석장"},
            {Constants.ZoneLSand, "모래 언덕"},
            {Constants.ZoneLFarmer, "농부"},
            {Constants.ZoneLMill, "제분소"},
            {Constants.Page1, "1 페이지"},
            {Constants.Page2, "2 페이지"},
            {Constants.Page3, "3 페이지"},
            {Constants.Page4, "4 페이지"},
            {Constants.Page5, "5 페이지"},
            {Constants.Page6, "6 페이지"},
            {Constants.Page7, "7 페이지"},
            {Constants.Page8, "8 페이지"},
            {Constants.Page9, "9 페이지"},
            {Constants.Page10, "10 페이지"},
            {Constants.CantUseHere, "여기서는 그걸 사용할 수 없어요, 사장님!"},
            {Constants.CustomLocations, "사용자 지정 위치"},
            {Constants.DontKnow, "그게 어디 있는지 몰라요!"},
            {Constants.InTutorial, "아직 그걸 할 수 없어요! 튜토리얼 때문이죠..."},
            {Constants.InTutorialNoStone, "아직 그걸 할 수 없어요! 튜토리얼 때문이죠 - 게다가 당신은 순간이동 돌이 없어요."},
            {Constants.M1, "내 동전은 어디 있지?"},
            {Constants.M10, "돈 줘, 친구."},
            {Constants.M2, "내놔."},
            {Constants.M3, "동전. 지금."},
            {Constants.M4, "금방 되찾을 거에요."},
            {Constants.M5, "이건 자선이 아니에요..."},
            {Constants.M6, "내놔, 친구."},
            {Constants.M7, "여행은 즐거웠나요?"},
            {Constants.M8, "또 여기인가?!"},
            {Constants.M9, "다 왔어요?"},
            {Constants.MoreCoin, "더 많은 동전이 필요해요!"},
            {Constants.WhereIsIt, "그 돌을 어디에 뒀더라..."}
        },
        ["ja"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "粘土採掘場"},
            {Constants.ZoneLCoal, "炭鉱脈"},
            {Constants.ZoneLFellingsite, "伐採現場"},
            {Constants.ZoneLLighthouse, "灯台"},
            {Constants.ZoneLQuarry, "採石場"},
            {Constants.ZoneLSand, "砂丘"},
            {Constants.ZoneLFarmer, "農夫"},
            {Constants.ZoneLMill, "風車"},
            {Constants.Page1, "ページ1"},
            {Constants.Page2, "ページ2"},
            {Constants.Page3, "ページ3"},
            {Constants.Page4, "ページ4"},
            {Constants.Page5, "ページ5"},
            {Constants.Page6, "ページ6"},
            {Constants.Page7, "ページ7"},
            {Constants.Page8, "ページ8"},
            {Constants.Page9, "ページ9"},
            {Constants.Page10, "ページ10"},
            {Constants.CantUseHere, "ここではそれを使えませんよ、ボス！"},
            {Constants.CustomLocations, "カスタムロケーション"},
            {Constants.DontKnow, "それがどこにあるのかわかりません！"},
            {Constants.InTutorial, "まだそれをすることはできません！チュートリアルに関することです…"},
            {Constants.InTutorialNoStone, "まだそれをすることはできません！チュートリアルに関すること - しかもテレポートストーンを持っていません。"},
            {Constants.M1, "私のコインはどこですか？"},
            {Constants.M10, "お金をよこせ、友よ。"},
            {Constants.M2, "渡してくれ。"},
            {Constants.M3, "コイン。今すぐ。"},
            {Constants.M4, "すぐに取り戻せるよ。"},
            {Constants.M5, "これは慈善事業じゃない..."},
            {Constants.M6, "出せよ、友よ。"},
            {Constants.M7, "楽しい旅だった？"},
            {Constants.M8, "またここですか？！"},
            {Constants.M9, "もう着いた？"},
            {Constants.MoreCoin, "もっとコインが必要だ！"},
            {Constants.WhereIsIt, "あの石はどこに置いたっけ…"}
        },
        ["ru"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Глиняный карьер"},
            {Constants.ZoneLCoal, "Угольная жила"},
            {Constants.ZoneLFellingsite, "Место рубки"},
            {Constants.ZoneLLighthouse, "Маяк"},
            {Constants.ZoneLQuarry, "Каменоломня"},
            {Constants.ZoneLSand, "Песчаная насыпь"},
            {Constants.ZoneLFarmer, "Фермер"},
            {Constants.ZoneLMill, "Мельница"},
            {Constants.Page1, "Страница 1"},
            {Constants.Page2, "Страница 2"},
            {Constants.Page3, "Страница 3"},
            {Constants.Page4, "Страница 4"},
            {Constants.Page5, "Страница 5"},
            {Constants.Page6, "Страница 6"},
            {Constants.Page7, "Страница 7"},
            {Constants.Page8, "Страница 8"},
            {Constants.Page9, "Страница 9"},
            {Constants.Page10, "Страница 10"},
            {Constants.CantUseHere, "Я не могу использовать это здесь, босс!"},
            {Constants.CustomLocations, "Пользовательские места"},
            {Constants.DontKnow, "Я не знаю, где это!"},
            {Constants.InTutorial, "Я пока не могу это сделать! Что-то насчёт туториала..."},
            {Constants.InTutorialNoStone, "Я пока не могу это сделать! Что-то насчёт туториала - и у тебя нет камня телепортации."},
            {Constants.M1, "Где мои деньги?"},
            {Constants.M10, "Деньги, приятель."},
            {Constants.M2, "Отдавай."},
            {Constants.M3, "Деньги. Сейчас."},
            {Constants.M4, "Ты быстро их вернёшь."},
            {Constants.M5, "Это не благотворительность..."},
            {Constants.M6, "Давай, приятель."},
            {Constants.M7, "Приятная поездка?"},
            {Constants.M8, "Снова здесь?!"},
            {Constants.M9, "Мы уже там?"},
            {Constants.MoreCoin, "Тебе нужно больше монет!"},
            {Constants.WhereIsIt, "Где я оставил этот камень..."}
        },
        ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Fossa di argilla"},
            {Constants.ZoneLCoal, "Vena di carbone"},
            {Constants.ZoneLFellingsite, "Sito di abbattimento"},
            {Constants.ZoneLLighthouse, "Faro"},
            {Constants.ZoneLQuarry, "Cava"},
            {Constants.ZoneLSand, "Cumulo di sabbia"},
            {Constants.ZoneLFarmer, "Contadino"},
            {Constants.ZoneLMill, "Mulino"},
            {Constants.Page1, "Pagina 1"},
            {Constants.Page2, "Pagina 2"},
            {Constants.Page3, "Pagina 3"},
            {Constants.Page4, "Pagina 4"},
            {Constants.Page5, "Pagina 5"},
            {Constants.Page6, "Pagina 6"},
            {Constants.Page7, "Pagina 7"},
            {Constants.Page8, "Pagina 8"},
            {Constants.Page9, "Pagina 9"},
            {Constants.Page10, "Pagina 10"},
            {Constants.CantUseHere, "Non posso usarlo qui, capo!"},
            {Constants.CustomLocations, "Posizioni Personalizzate"},
            {Constants.DontKnow, "Non so dove sia!"},
            {Constants.InTutorial, "Non posso farlo ancora! Qualcosa a proposito di un tutorial..."},
            {Constants.InTutorialNoStone, "Non posso farlo ancora! Qualcosa a proposito di un tutorial - e non hai una pietra di teletrasporto."},
            {Constants.M1, "Dov'è la mia moneta?"},
            {Constants.M10, "Soldi, amico."},
            {Constants.M2, "Consegna."},
            {Constants.M3, "Moneta. Ora."},
            {Constants.M4, "Lo recupererai in un attimo."},
            {Constants.M5, "Questa non è una carità..."},
            {Constants.M6, "Sborsa amico."},
            {Constants.M7, "Viaggio piacevole?"},
            {Constants.M8, "Di nuovo qui?!"},
            {Constants.M9, "Siamo già arrivati?"},
            {Constants.MoreCoin, "Hai bisogno di più monete!"},
            {Constants.WhereIsIt, "Dove ho lasciato quella pietra..."}
        },
        ["pl"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            {Constants.ZoneLClay, "Złoże gliny"},
            {Constants.ZoneLCoal, "Złoże węgla"},
            {Constants.ZoneLFellingsite, "Miejsce wyrębu"},
            {Constants.ZoneLLighthouse, "Latarnia morska"},
            {Constants.ZoneLQuarry, "Kamieniołom"},
            {Constants.ZoneLSand, "Kopiec piasku"},
            {Constants.ZoneLFarmer, "Rolnik"},
            {Constants.ZoneLMill, "Młyn"},
            {Constants.Page1, "Strona 1"},
            {Constants.Page2, "Strona 2"},
            {Constants.Page3, "Strona 3"},
            {Constants.Page4, "Strona 4"},
            {Constants.Page5, "Strona 5"},
            {Constants.Page6, "Strona 6"},
            {Constants.Page7, "Strona 7"},
            {Constants.Page8, "Strona 8"},
            {Constants.Page9, "Strona 9"},
            {Constants.Page10, "Strona 10"},
            {Constants.CantUseHere, "Nie mogę tego tutaj użyć, szefie!"},
            {Constants.CustomLocations, "Lokalizacje niestandardowe"},
            {Constants.DontKnow, "Nie wiem, gdzie to jest!"},
            {Constants.InTutorial, "Jeszcze nie mogę tego zrobić! Coś o samouczku..."},
            {Constants.InTutorialNoStone, "Jeszcze nie mogę tego zrobić! Coś o samouczku - i nie masz kamienia teleportacji."},
            {Constants.M1, "Gdzie jest moja moneta?"},
            {Constants.M10, "Pieniądze, kolego."},
            {Constants.M2, "Oddaj."},
            {Constants.M3, "Moneta. Teraz."},
            {Constants.M4, "Odzyskasz to w mgnieniu oka."},
            {Constants.M5, "To nie jest dobroczynność..."},
            {Constants.M6, "Wyłóż to, kolego."},
            {Constants.M7, "Przyjemna podróż?"},
            {Constants.M8, "Znowu tutaj?!"},
            {Constants.M9, "Czy już tam jesteśmy?"},
            {Constants.MoreCoin, "Potrzebujesz więcej monet!"},
            {Constants.WhereIsIt, "Gdzie zostawiłem ten kamień..."}
        }
    };

    internal static Terms GetTerm(string term)
    {
        var exists = TermMap.FirstOrDefault(x => x.Value == term);
        return exists.Value != null ? exists.Key : Terms.None;
    }


    internal static string GetTranslation(Terms term)
    {
        var lang = GJL.GetCurLng();
        lang = lang.Replace('_', '-').ToLower();
        if (LanguageDictionaries.TryGetValue(lang, out var dict))
        {
            return dict.TryGetValue(TermMap[term], out var translation) ? translation : TermMap[term];
        }
        return TermMap[term];
    }
}