//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeamMeUpGerry.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeamMeUpGerry.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t use that here, boss!.
        /// </summary>
        public static string CantUseHere {
            get {
                return ResourceManager.GetString("CantUseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay pit.
        /// </summary>
        public static string Clay {
            get {
                return ResourceManager.GetString("Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal vein.
        /// </summary>
        public static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know where that is!.
        /// </summary>
        public static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        public static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t do that just yet! Something about a tutorial…..
        /// </summary>
        public static string InTutorial {
            get {
                return ResourceManager.GetString("InTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t do that just yet! Something about a tutorial - and you don’t have a teleport stone..
        /// </summary>
        public static string InTutorialNoStone {
            get {
                return ResourceManager.GetString("InTutorialNoStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s my coin?.
        /// </summary>
        public static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money buddy..
        /// </summary>
        public static string M10 {
            get {
                return ResourceManager.GetString("M10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand it over..
        /// </summary>
        public static string M2 {
            get {
                return ResourceManager.GetString("M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin. Now..
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll make it back in no time..
        /// </summary>
        public static string M4 {
            get {
                return ResourceManager.GetString("M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This isn&apos;t a charity....
        /// </summary>
        public static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cough it up buddy..
        /// </summary>
        public static string M6 {
            get {
                return ResourceManager.GetString("M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasant trip?.
        /// </summary>
        public static string M7 {
            get {
                return ResourceManager.GetString("M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here again?!.
        /// </summary>
        public static string M8 {
            get {
                return ResourceManager.GetString("M8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are we there yet?.
        /// </summary>
        public static string M9 {
            get {
                return ResourceManager.GetString("M9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mill.
        /// </summary>
        public static string Mill {
            get {
                return ResourceManager.GetString("Mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need more coin!.
        /// </summary>
        public static string MoreCoin {
            get {
                return ResourceManager.GetString("MoreCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use that yet!.
        /// </summary>
        public static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleportstone Ready!.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand mound.
        /// </summary>
        public static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did I leave that stone....
        /// </summary>
        public static string WhereIsIt {
            get {
                return ResourceManager.GetString("WhereIsIt", resourceCulture);
            }
        }
    }
}
