//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrayTheDayAway.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayTheDayAway.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darn it! Lost another one....
        /// </summary>
        public static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aw heck, there goes another....
        /// </summary>
        public static string M2 {
            get {
                return ResourceManager.GetString("M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blimey! Losing them I&apos;m losing my teeth!.
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady luck is not on my side today....
        /// </summary>
        public static string M4 {
            get {
                return ResourceManager.GetString("M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aw...come on man, I just crafted that one!.
        /// </summary>
        public static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Gerry&apos;s sake...not another one!.
        /// </summary>
        public static string M6 {
            get {
                return ResourceManager.GetString("M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I give up, take them, take them all!.
        /// </summary>
        public static string M7 {
            get {
                return ResourceManager.GetString("M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now where did I put that prayer....oh..
        /// </summary>
        public static string M8 {
            get {
                return ResourceManager.GetString("M8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigh..
        /// </summary>
        public static string M9 {
            get {
                return ResourceManager.GetString("M9", resourceCulture);
            }
        }
    }
}
