//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLootHeavies.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoLootHeavies.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump ore here!.
        /// </summary>
        public static string DumpOre {
            get {
                return ResourceManager.GetString("DumpOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump stone &amp; marble here!.
        /// </summary>
        public static string DumpStone {
            get {
                return ResourceManager.GetString("DumpStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump timber here!.
        /// </summary>
        public static string DumpTimber {
            get {
                return ResourceManager.GetString("DumpTimber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...ore storage is now full!.
        /// </summary>
        public static string OreFull {
            get {
                return ResourceManager.GetString("OreFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...stone storage is now full!.
        /// </summary>
        public static string StoneFull {
            get {
                return ResourceManager.GetString("StoneFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to dump sites when all stockpiles are full is now OFF..
        /// </summary>
        public static string TeleOff {
            get {
                return ResourceManager.GetString("TeleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to dump sites when all stockpiles are full is now ON..
        /// </summary>
        public static string TeleOn {
            get {
                return ResourceManager.GetString("TeleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...timber storage is now full!.
        /// </summary>
        public static string TimberFull {
            get {
                return ResourceManager.GetString("TimberFull", resourceCulture);
            }
        }
    }
}
