//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Resources;
using System.Runtime.CompilerServices;

namespace BeamMeUpGerry.lang {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("BeamMeUpGerry.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t use that here, boss!.
        /// </summary>
        internal static string CantUseHere {
            get {
                return ResourceManager.GetString("CantUseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay pit.
        /// </summary>
        internal static string Clay {
            get {
                return ResourceManager.GetString("Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal vein.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Locations.
        /// </summary>
        internal static string Custom_Locations {
            get {
                return ResourceManager.GetString("Custom Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know where that is!.
        /// </summary>
        internal static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        internal static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t do that just yet! Something about a tutorial…..
        /// </summary>
        internal static string InTutorial {
            get {
                return ResourceManager.GetString("InTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can’t do that just yet! Something about a tutorial - and you don’t have a teleport stone..
        /// </summary>
        internal static string InTutorialNoStone {
            get {
                return ResourceManager.GetString("InTutorialNoStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s my coin?.
        /// </summary>
        internal static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money buddy..
        /// </summary>
        internal static string M10 {
            get {
                return ResourceManager.GetString("M10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand it over..
        /// </summary>
        internal static string M2 {
            get {
                return ResourceManager.GetString("M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin. Now..
        /// </summary>
        internal static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll make it back in no time..
        /// </summary>
        internal static string M4 {
            get {
                return ResourceManager.GetString("M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This isn&apos;t a charity....
        /// </summary>
        internal static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cough it up buddy..
        /// </summary>
        internal static string M6 {
            get {
                return ResourceManager.GetString("M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasant trip?.
        /// </summary>
        internal static string M7 {
            get {
                return ResourceManager.GetString("M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here again?!.
        /// </summary>
        internal static string M8 {
            get {
                return ResourceManager.GetString("M8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are we there yet?.
        /// </summary>
        internal static string M9 {
            get {
                return ResourceManager.GetString("M9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mill.
        /// </summary>
        internal static string Mill {
            get {
                return ResourceManager.GetString("Mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need more coin!.
        /// </summary>
        internal static string MoreCoin {
            get {
                return ResourceManager.GetString("MoreCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 1.
        /// </summary>
        internal static string Page_1 {
            get {
                return ResourceManager.GetString("Page 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 10.
        /// </summary>
        internal static string Page_10 {
            get {
                return ResourceManager.GetString("Page 10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 2.
        /// </summary>
        internal static string Page_2 {
            get {
                return ResourceManager.GetString("Page 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 3.
        /// </summary>
        internal static string Page_3 {
            get {
                return ResourceManager.GetString("Page 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 4.
        /// </summary>
        internal static string Page_4 {
            get {
                return ResourceManager.GetString("Page 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 5.
        /// </summary>
        internal static string Page_5 {
            get {
                return ResourceManager.GetString("Page 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 6.
        /// </summary>
        internal static string Page_6 {
            get {
                return ResourceManager.GetString("Page 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 7.
        /// </summary>
        internal static string Page_7 {
            get {
                return ResourceManager.GetString("Page 7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 8.
        /// </summary>
        internal static string Page_8 {
            get {
                return ResourceManager.GetString("Page 8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 9.
        /// </summary>
        internal static string Page_9 {
            get {
                return ResourceManager.GetString("Page 9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand mound.
        /// </summary>
        internal static string Sand {
            get {
                return ResourceManager.GetString("Sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did I leave that stone....
        /// </summary>
        internal static string WhereIsIt {
            get {
                return ResourceManager.GetString("WhereIsIt", resourceCulture);
            }
        }
    }
}