//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveNow.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveNow.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save here, boss!.
        /// </summary>
        public static string CantSaveHere {
            get {
                return ResourceManager.GetString("CantSaveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to desktop.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSave.
        /// </summary>
        public static string InfoAutoSave {
            get {
                return ResourceManager.GetString("InfoAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string InfoMinutes {
            get {
                return ResourceManager.GetString("InfoMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Save on Auto Save.
        /// </summary>
        public static string InfoNewSaveOnAutoSave {
            get {
                return ResourceManager.GetString("InfoNewSaveOnAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string InfoPeriod {
            get {
                return ResourceManager.GetString("InfoPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves to keep.
        /// </summary>
        public static string InfoSavesToKeep {
            get {
                return ResourceManager.GetString("InfoSavesToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What a rush! Gets me every time!.
        /// </summary>
        public static string Rush {
            get {
                return ResourceManager.GetString("Rush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit to desktop.
        /// </summary>
        public static string SaveAreYouSureDesktop {
            get {
                return ResourceManager.GetString("SaveAreYouSureDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return to the main menu.
        /// </summary>
        public static string SaveAreYouSureMenu {
            get {
                return ResourceManager.GetString("SaveAreYouSureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved!.
        /// </summary>
        public static string SaveMessage {
            get {
                return ResourceManager.GetString("SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress and current location will not be saved.
        /// </summary>
        public static string SaveProgressNotSaved {
            get {
                return ResourceManager.GetString("SaveProgressNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress and current location will be saved.
        /// </summary>
        public static string SaveProgressSaved {
            get {
                return ResourceManager.GetString("SaveProgressSaved", resourceCulture);
            }
        }
    }
}
