// Decompiled with JetBrains decompiler
// Type: FollowerClothingType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: B4944960-D044-4E12-B091-6A0422C77B16
// Assembly location: F:\OneDrive\Development\Game-Mods\Cult of the Lamb\libs\Assembly-CSharp.dll

#nullable disable
public enum FollowerClothingType
{
  None,
  Jumper,
  Singlet,
  Shirt,
  Robe,
  Robes_Baal,
  Robes_Aym,
  Robes_Fancy,
  Warrior,
  Raincoat,
  Suit_Fancy,
  Cultist_DLC,
  Cultist_DLC2,
  Heretic_DLC,
  Heretic_DLC2,
  DLC_1,
  DLC_2,
  DLC_3,
  DLC_4,
  DLC_5,
  Special_1,
  Special_2,
  Special_3,
  Special_4,
  Special_5,
  Special_6,
  Special_7,
  Normal_1,
  Normal_2,
  Normal_3,
  Normal_4,
  Normal_5,
  Normal_6,
  Normal_7,
  Normal_8,
  Normal_9,
  Normal_10,
  Normal_11,
  Normal_12,
  Naked,
  Count,
  DLC_6,
  Pilgrim_DLC,
  Pilgrim_DLC2,
  Winter_1,
  Winter_2,
  Winter_3,
  Winter_4,
  Winter_5,
  Winter_6,
  Normal_MajorDLC_1,
  Normal_MajorDLC_2,
  Normal_MajorDLC_3,
  Normal_MajorDLC_4,
  Normal_MajorDLC_5,
  Normal_MajorDLC_6,
  Apple_1,
  Apple_2,
}
