namespace DecompDelight;

internal static class LangDicts
{
    private readonly static Dictionary<string, Dictionary<ElementMaps.Element, string>> LanguageDictionaries = new()
    {
        ["en"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Slowing"},
            {ElementMaps.Element.Acceleration, "Acceleration"},
            {ElementMaps.Element.Health, "Health"},
            {ElementMaps.Element.Death, "Death"},
            {ElementMaps.Element.Order, "Order"},
            {ElementMaps.Element.Toxic, "Toxic"},
            {ElementMaps.Element.Chaos, "Chaos"},
            {ElementMaps.Element.Life, "Life"},
            {ElementMaps.Element.Electric, "Electric"},
            {ElementMaps.Element.Silver, "Silver"},
            {ElementMaps.Element.None, "None"},
            {ElementMaps.Element.White, "White"},
            {ElementMaps.Element.Water, "Water"},
            {ElementMaps.Element.Oil, "Oil"},
            {ElementMaps.Element.Alcohol, "Alcohol"},
            {ElementMaps.Element.Blood, "Blood"},
            {ElementMaps.Element.Salt, "Salt"},
            {ElementMaps.Element.Ash, "Ash"},
        },
        ["fr"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Ralentissement"},
            {ElementMaps.Element.Acceleration, "Accélération"},
            {ElementMaps.Element.Health, "Santé"},
            {ElementMaps.Element.Death, "Mort"},
            {ElementMaps.Element.Order, "Ordre"},
            {ElementMaps.Element.Toxic, "Toxique"},
            {ElementMaps.Element.Chaos, "Chaos"},
            {ElementMaps.Element.Life, "Vie"},
            {ElementMaps.Element.Electric, "Électrique"},
            {ElementMaps.Element.Silver, "Argent"},
            {ElementMaps.Element.None, "Aucun"},
            {ElementMaps.Element.White, "Blanc"},
            {ElementMaps.Element.Water, "Eau"},
            {ElementMaps.Element.Oil, "Huile"},
            {ElementMaps.Element.Alcohol, "Alcool"},
            {ElementMaps.Element.Blood, "Sang"},
            {ElementMaps.Element.Salt, "Sel"},
            {ElementMaps.Element.Ash, "Cendre"},
        },
        ["de"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Verlangsamung"},
            {ElementMaps.Element.Acceleration, "Beschleunigung"},
            {ElementMaps.Element.Health, "Gesundheit"},
            {ElementMaps.Element.Death, "Tod"},
            {ElementMaps.Element.Order, "Ordnung"},
            {ElementMaps.Element.Toxic, "Toxisch"},
            {ElementMaps.Element.Chaos, "Chaos"},
            {ElementMaps.Element.Life, "Leben"},
            {ElementMaps.Element.Electric, "Elektrisch"},
            {ElementMaps.Element.Silver, "Silber"},
            {ElementMaps.Element.None, "Keiner"},
            {ElementMaps.Element.White, "Weiß"},
            {ElementMaps.Element.Water, "Wasser"},
            {ElementMaps.Element.Oil, "Öl"},
            {ElementMaps.Element.Alcohol, "Alkohol"},
            {ElementMaps.Element.Blood, "Blut"},
            {ElementMaps.Element.Salt, "Salz"},
            {ElementMaps.Element.Ash, "Asche"},
        },
        ["zh_cn"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "减速"},
            {ElementMaps.Element.Acceleration, "加速"},
            {ElementMaps.Element.Health, "生命"},
            {ElementMaps.Element.Death, "死亡"},
            {ElementMaps.Element.Order, "秩序"},
            {ElementMaps.Element.Toxic, "有毒"},
            {ElementMaps.Element.Chaos, "混沌"},
            {ElementMaps.Element.Life, "生命"},
            {ElementMaps.Element.Electric, "电"},
            {ElementMaps.Element.Silver, "银"},
            {ElementMaps.Element.None, "无"},
            {ElementMaps.Element.White, "白"},
            {ElementMaps.Element.Water, "水"},
            {ElementMaps.Element.Oil, "油"},
            {ElementMaps.Element.Alcohol, "酒精"},
            {ElementMaps.Element.Blood, "血液"},
            {ElementMaps.Element.Salt, "盐"},
            {ElementMaps.Element.Ash, "灰烬"},
        },
        ["es"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Ralentización"},
            {ElementMaps.Element.Acceleration, "Aceleración"},
            {ElementMaps.Element.Health, "Salud"},
            {ElementMaps.Element.Death, "Muerte"},
            {ElementMaps.Element.Order, "Orden"},
            {ElementMaps.Element.Toxic, "Tóxico"},
            {ElementMaps.Element.Chaos, "Caos"},
            {ElementMaps.Element.Life, "Vida"},
            {ElementMaps.Element.Electric, "Eléctrico"},
            {ElementMaps.Element.Silver, "Plata"},
            {ElementMaps.Element.None, "Ninguno"},
            {ElementMaps.Element.White, "Blanco"},
            {ElementMaps.Element.Water, "Agua"},
            {ElementMaps.Element.Oil, "Aceite"},
            {ElementMaps.Element.Alcohol, "Alcohol"},
            {ElementMaps.Element.Blood, "Sangre"},
            {ElementMaps.Element.Salt, "Sal"},
            {ElementMaps.Element.Ash, "Ceniza"},
        },
        ["pt-br"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Desaceleração"},
            {ElementMaps.Element.Acceleration, "Aceleração"},
            {ElementMaps.Element.Health, "Saúde"},
            {ElementMaps.Element.Death, "Morte"},
            {ElementMaps.Element.Order, "Ordem"},
            {ElementMaps.Element.Toxic, "Tóxico"},
            {ElementMaps.Element.Chaos, "Caos"},
            {ElementMaps.Element.Life, "Vida"},
            {ElementMaps.Element.Electric, "Elétrico"},
            {ElementMaps.Element.Silver, "Prata"},
            {ElementMaps.Element.None, "Nenhum"},
            {ElementMaps.Element.White, "Branco"},
            {ElementMaps.Element.Water, "Água"},
            {ElementMaps.Element.Oil, "Óleo"},
            {ElementMaps.Element.Alcohol, "Álcool"},
            {ElementMaps.Element.Blood, "Sangue"},
            {ElementMaps.Element.Salt, "Sal"},
            {ElementMaps.Element.Ash, "Cinza"},
        },
        ["ko"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "감속"},
            {ElementMaps.Element.Acceleration, "가속"},
            {ElementMaps.Element.Health, "건강"},
            {ElementMaps.Element.Death, "죽음"},
            {ElementMaps.Element.Order, "질서"},
            {ElementMaps.Element.Toxic, "독성"},
            {ElementMaps.Element.Chaos, "혼돈"},
            {ElementMaps.Element.Life, "생명"},
            {ElementMaps.Element.Electric, "전기"},
            {ElementMaps.Element.Silver, "은"},
            {ElementMaps.Element.None, "없음"},
            {ElementMaps.Element.White, "흰색"},
            {ElementMaps.Element.Water, "물"},
            {ElementMaps.Element.Oil, "기름"},
            {ElementMaps.Element.Alcohol, "알코올"},
            {ElementMaps.Element.Blood, "피"},
            {ElementMaps.Element.Salt, "소금"},
            {ElementMaps.Element.Ash, "재"},
        },
        ["ja"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "減速"},
            {ElementMaps.Element.Acceleration, "加速"},
            {ElementMaps.Element.Health, "健康"},
            {ElementMaps.Element.Death, "死"},
            {ElementMaps.Element.Order, "秩序"},
            {ElementMaps.Element.Toxic, "有毒"},
            {ElementMaps.Element.Chaos, "混沌"},
            {ElementMaps.Element.Life, "生命"},
            {ElementMaps.Element.Electric, "電気"},
            {ElementMaps.Element.Silver, "銀"},
            {ElementMaps.Element.None, "なし"},
            {ElementMaps.Element.White, "白"},
            {ElementMaps.Element.Water, "水"},
            {ElementMaps.Element.Oil, "油"},
            {ElementMaps.Element.Alcohol, "アルコール"},
            {ElementMaps.Element.Blood, "血液"},
            {ElementMaps.Element.Salt, "塩"},
            {ElementMaps.Element.Ash, "灰"},
        },
        ["ru"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Замедление"},
            {ElementMaps.Element.Acceleration, "Ускорение"},
            {ElementMaps.Element.Health, "Здоровье"},
            {ElementMaps.Element.Death, "Смерть"},
            {ElementMaps.Element.Order, "Порядок"},
            {ElementMaps.Element.Toxic, "Токсичный"},
            {ElementMaps.Element.Chaos, "Хаос"},
            {ElementMaps.Element.Life, "Жизнь"},
            {ElementMaps.Element.Electric, "Электрический"},
            {ElementMaps.Element.Silver, "Серебро"},
            {ElementMaps.Element.None, "Нет"},
            {ElementMaps.Element.White, "Белый"},
            {ElementMaps.Element.Water, "Вода"},
            {ElementMaps.Element.Oil, "Масло"},
            {ElementMaps.Element.Alcohol, "Алкоголь"},
            {ElementMaps.Element.Blood, "Кровь"},
            {ElementMaps.Element.Salt, "Соль"},
            {ElementMaps.Element.Ash, "Пепел"},
        },
        ["it"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Rallentamento"},
            {ElementMaps.Element.Acceleration, "Accelerazione"},
            {ElementMaps.Element.Health, "Salute"},
            {ElementMaps.Element.Death, "Morte"},
            {ElementMaps.Element.Order, "Ordine"},
            {ElementMaps.Element.Toxic, "Tossico"},
            {ElementMaps.Element.Chaos, "Caos"},
            {ElementMaps.Element.Life, "Vita"},
            {ElementMaps.Element.Electric, "Elettrico"},
            {ElementMaps.Element.Silver, "Argento"},
            {ElementMaps.Element.None, "Nessuno"},
            {ElementMaps.Element.White, "Bianco"},
            {ElementMaps.Element.Water, "Acqua"},
            {ElementMaps.Element.Oil, "Olio"},
            {ElementMaps.Element.Alcohol, "Alcool"},
            {ElementMaps.Element.Blood, "Sangue"},
            {ElementMaps.Element.Salt, "Sale"},
            {ElementMaps.Element.Ash, "Cenere"},
        },
        ["pl"] = new Dictionary<ElementMaps.Element, string>
        {
            {ElementMaps.Element.Slowing, "Spowolnienie"},
            {ElementMaps.Element.Acceleration, "Przyspieszenie"},
            {ElementMaps.Element.Health, "Zdrowie"},
            {ElementMaps.Element.Death, "Śmierć"},
            {ElementMaps.Element.Order, "Porządek"},
            {ElementMaps.Element.Toxic, "Toksyczny"},
            {ElementMaps.Element.Chaos, "Chaos"},
            {ElementMaps.Element.Life, "Życie"},
            {ElementMaps.Element.Electric, "Elektryczność"},
            {ElementMaps.Element.Silver, "Srebro"},
            {ElementMaps.Element.None, "Brak"},
            {ElementMaps.Element.White, "Biały"},
            {ElementMaps.Element.Water, "Woda"},
            {ElementMaps.Element.Oil, "Olej"},
            {ElementMaps.Element.Alcohol, "Alkohol"},
            {ElementMaps.Element.Blood, "Krew"},
            {ElementMaps.Element.Salt, "Sól"},
            {ElementMaps.Element.Ash, "Popiół"},
        }
    };

    internal static string GetElementName(ElementMaps.Element element)
    {
        var lang = GJL.GetCurLng();
        return LanguageDictionaries.TryGetValue(lang, out var dict) ? dict[element] : LanguageDictionaries["en"][element];
    }
}