//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtfulReminders.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtfulReminders.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmmm what day is it? ....
        /// </summary>
        public static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Reloaded!.
        /// </summary>
        public static string ConfigMessage {
            get {
                return ResourceManager.GetString("ConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Envy....
        /// </summary>
        public static string dEnvy {
            get {
                return ResourceManager.GetString("dEnvy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Gluttony....
        /// </summary>
        public static string dGluttony {
            get {
                return ResourceManager.GetString("dGluttony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Envy ....
        /// </summary>
        public static string dhEnvy {
            get {
                return ResourceManager.GetString("dhEnvy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Gluttony...should see the merchant today....
        /// </summary>
        public static string dhGluttony {
            get {
                return ResourceManager.GetString("dhGluttony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Lust...could drop by the tavern....
        /// </summary>
        public static string dhLust {
            get {
                return ResourceManager.GetString("dhLust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Pride...might go see the bishop....
        /// </summary>
        public static string dhPride {
            get {
                return ResourceManager.GetString("dhPride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Pride...can&apos;t forget my sermon today....
        /// </summary>
        public static string dhPrideSermon {
            get {
                return ResourceManager.GetString("dhPrideSermon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Sloth...wonder what the astrologer is up to....
        /// </summary>
        public static string dhSloth {
            get {
                return ResourceManager.GetString("dhSloth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Wrath...wonder if there&apos;s anything to burn....
        /// </summary>
        public static string dhWrath {
            get {
                return ResourceManager.GetString("dhWrath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Lust....
        /// </summary>
        public static string dLust {
            get {
                return ResourceManager.GetString("dLust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Pride....
        /// </summary>
        public static string dPride {
            get {
                return ResourceManager.GetString("dPride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Sloth....
        /// </summary>
        public static string dSloth {
            get {
                return ResourceManager.GetString("dSloth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Wrath....
        /// </summary>
        public static string dWrath {
            get {
                return ResourceManager.GetString("dWrath", resourceCulture);
            }
        }
    }
}
