// Global using directives

global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Reflection.Emit;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using CultOfQoL.Patches;
global using DG.Tweening;
global using HarmonyLib;
global using JetBrains.Annotations;
global using Lamb.UI;
global using Lamb.UI.FollowerInteractionWheel;
global using Lamb.UI.FollowerSelect;
global using Lamb.UI.MainMenu;
global using Lamb.UI.PauseMenu;
global using Lamb.UI.KitchenMenu;
global using Lamb.UI.RefineryMenu;
global using LeTai.Asset.TranslucentImage;
global using Map;
global using MMTools;
global using MonoMod.Utils;
global using Newtonsoft.Json;
global using Shared;
global using src.UI.Menus;
global using UnityEngine;
global using UnityEngine.SceneManagement;
global using UnityEngine.UI;
global using Debug = UnityEngine.Debug;
global using Debugger = DG.Tweening.Core.Debugger;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;