// Decompiled with JetBrains decompiler
// Type: FollowerCommands
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D4FAC018-F15B-4650-BC23-66B6B15D1655
// Assembly location: G:\CultOfTheLambPreRitualNerf\depots\1313141\21912051\Cult Of The Lamb_Data\Managed\Assembly-CSharp.dll

using System;

#nullable disable
[Serializable]
public enum FollowerCommands
{
  None,
  GiveWorkerCommand_2,
  ChangeRole,
  GiveItem,
  Talk,
  MakeDemand,
  BedRest,
  Murder,
  ExtortMoney,
  Dance,
  DemandDevotion,
  Gift,
  Imprison,
  SendToHospital,
  CutTrees,
  ForageBerries,
  ClearWeeds,
  ClearRubble,
  TellMeYourProblems,
  DemandLoyalty,
  Punish,
  BeNice,
  Romance,
  WakeUp,
  LevelUp,
  EatSomething,
  Sleep,
  WorshipAtShrine,
  Build,
  NoAvailablePrisons,
  Cook_2,
  Meal,
  MealGrass,
  MealPoop,
  MealGoodFish,
  MealFollowerMeat,
  MealGreat,
  MealMushrooms,
  MealMeat,
  AreYouSure,
  AreYouSureYes,
  AreYouSureNo,
  Study,
  Intimidate,
  Bribe,
  Ascend,
  Surveillance,
  Farmer_2,
  FaithEnforcer,
  TaxEnforcer,
  CollectTax,
  Gift_Small,
  Gift_Medium,
  Gift_Necklace1,
  Gift_Necklace2,
  Gift_Necklace3,
  Gift_Necklace4,
  Gift_Necklace5,
  Janitor_2,
  Bless,
  MealGreatFish,
  MealBadFish,
  RemoveNecklace,
  Reeducate,
  Refiner_2,
  MealBerries,
  MealMediumVeg,
  MealMixedLow,
  MealMixedMedium,
  MealMixedHigh,
  MealDeadly,
  MealMeatLow,
  MealMeatHigh,
  ViewTraits,
  NextPage,
  PetDog,
}
