// Decompiled with JetBrains decompiler
// Type: FollowerTaskType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D4FAC018-F15B-4650-BC23-66B6B15D1655
// Assembly location: G:\CultOfTheLambPreRitualNerf\depots\1313141\21912051\Cult Of The Lamb_Data\Managed\Assembly-CSharp.dll

#nullable disable
public enum FollowerTaskType
{
  None,
  ManualControl,
  Idle,
  Build,
  ExitChurch,
  Imprisoned,
  EatMeal,
  Sleep,
  Ill,
  Farm,
  Dissent,
  DissentListen,
  ReactVomit,
  BuryBody,
  Pray,
  FollowPlayer,
  ClaimDwelling,
  Starving,
  FakeWork,
  FakeLeisure,
  Study,
  AttendTeaching,
  Chat,
  DanceCircleLead,
  DanceCircleFollow,
  ClearRubble,
  ClearWeeds,
  Lumberjack,
  DepositWood,
  DanceFirePit,
  Research,
  Forage,
  ChopTrees,
  GreetPlayer,
  ReactCorpse,
  Fisherman,
  ChangeLocation,
  Bathroom,
  AssistRitual,
  ReactPoop,
  CleanWaste,
  EatStoredFood,
  LeaveCult,
  FindPlaceToDie,
  MineBloodStone,
  Vomit,
  InHealing,
  AwaitInstructions,
  GetPlayerAttention,
  SleepBedRest,
  Cook,
  ReactOuthouse,
  Blacksmith,
  Refinery,
  PassivePray,
  OldAge,
  AwaitConsuming,
  ClearRubbleBig,
  ResourceStation,
  ReactDecoration,
  MissionaryInProgress,
  MissionaryComplete,
  ReactGrave,
  EatFeastTable,
  Janitor,
  IsDemon,
  Zombie,
  ZombieKillFollower,
  FaithEnforce,
  TaxEnforce,
  IllPoopy,
  ReactPrisoner,
  ReactSpookedFromGhost,
}
