// Decompiled with JetBrains decompiler
// Type: Objectives
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D4FAC018-F15B-4650-BC23-66B6B15D1655
// Assembly location: G:\CultOfTheLambPreRitualNerf\depots\1313141\21912051\Cult Of The Lamb_Data\Managed\Assembly-CSharp.dll

#nullable disable
public class Objectives
{
  public enum TYPES
  {
    NONE,
    COLLECT_ITEM,
    BUILD_STRUCTURE,
    RECRUIT_FOLLOWER,
    DEPOSIT_FOOD,
    CUSTOM,
    STARVING_FOLLOWER,
    LOW_FAITH_FOLLOWER,
    KILL_ENEMIES,
    NO_DODGE,
    NO_DAMAGE,
    NO_CURSES,
    NO_HEALING,
    SHOOT_DUMMIES,
    REMOVE_STRUCTURES,
    SEND_FOLLOWER_BED_REST,
    TALK_TO_FOLLOWER,
    COOK_MEALS,
    PLACE_STRUCTURES,
    PERFORM_RITUAL,
    UNLOCK,
    EAT_MEAL,
    RECRUIT_CURSED_FOLLOWER,
    FIND_FOLLOWER,
    DEFEAT_KNUCKLEBONES,
  }

  public enum CustomQuestTypes
  {
    None,
    Test,
    BringSozoMushrooms,
    CureIllness,
    CureDissenter,
    RepairTheShrine,
    CookFirstMeal,
    GiveSermon,
    IndoctrinateNewRecruit,
    GoToDungeon,
    GetNewFollowersFromDungeon,
    UnlockSacredKnowledge,
    PerformRitual,
    CollectDivineInspiration,
    DestroyBodiesForBones,
    KillABossAndTakeTheirHeart,
    BringMonsterHeartToRatau,
    ShootCurse,
    HoldToAim,
    PlantCrops,
    WaterCrops,
    CleanUpVomit,
    CleanUpPoop,
    SendFollowerToBedRest,
    CatchFish,
    FixTheLighthouse,
    NameCult,
    ZombieExists,
    AddFuelToCookingFire,
    SendFollowerToPrison,
    SendFollowerOnMissionary,
    UseFeastTable,
    UseFirePit,
    GetFollowerUpgradePoint,
    MurderFollower,
    MurderFollowerAtNight,
    Disciple,
    BuryBody,
    VisitFisherman,
    VisitRatau,
    VisitSozo,
    VisitPlimbo,
    VisitMidas,
    UnlockFleece,
    PlimboEye1,
    PlimboEye2,
    PlimboEye3,
    PlimboEye4,
    PayMidas,
    FollowerRecoverIllness,
    GetMoreGoldFromDungeon,
    MonsterHeart,
    KillFollower,
    BishopsOfTheOldFaith1,
    BishopsOfTheOldFaith2,
    BishopsOfTheOldFaith3,
    BishopsOfTheOldFaith4,
    FreeDeathCat,
    CrisisOfFaith,
    SozoPerformRitual,
    SozoReturn,
    GameOver,
    GiveGift,
    DeclareDoctrine,
    BlessAFollower,
    LoyaltyCollectReward,
    PerformAnyRitual,
    FindDoctrineStone,
    LighthouseReturn,
    CatchSquid,
    CatchOctopus,
    CatchLobster,
    CatchCrab,
    BringSozoMushrooms2,
    ReadMind,
  }
}
